name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag flask-app:$(date +%s)
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: "ipdocker"
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the Docker image
      run: docker push ipdocker/flask-app:$(date +%s)
      env:
        DOCKER_BUILDKIT: 1