name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker image tag
      id: vars
      run: echo "TAG=$(date +%s)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ipdocker/flask-app:${{ env.TAG }}
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: "ipdocker"
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the Docker image
      run: docker push ipdocker/flask-app:${{ env.TAG }}
      env:
        DOCKER_BUILDKIT: 1
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Run tests
      run: |
        docker run --rm -d ipdocker/flask-app:${{ env.TAG }} --port 5000
        curl --retry 5 --retry-connrefused --retry-delay 10 http://localhost:5000
        docker stop $(docker ps -q --filter ancestor=ipdocker/flask-app:${{ env.TAG }})
        docker rmi ipdocker/flask-app:${{ env.TAG }}
