name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:

    name: build-and-push
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.set-tag.outputs.image-tag }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker image tag
      id: vars
      run: echo "image-tag=$(date +%s)" >> "$GITHUB_OUTPUTS"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ipdocker/flask-app:${{ steps.set-tag.outputs.image-tag }}
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: "ipdocker"
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push the Docker image
      run: docker push ipdocker/flask-app:${{ steps.set-tag.outputs.image-tag }}
      env:
        DOCKER_BUILDKIT: 1
  
  run-image:
    name: Pull and Run Docker Image
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull Docker image
        run: docker pull ${{ needs.build-and-push.outputs.image-tag }}

      - name: Run Docker container
        run: docker run --rm ${{ needs.build-and-push.outputs.image-tag }}
 